// i18n/locales/en.ts
export default {
  // Navigation
  home: "Home",
  study: "Study",
  quiz: "Quiz",
  planning: "Planning",
  chat: "AI Chat",
  profile: "Profile",

  // Home
  hello: "Hello",
  studyai_desc: "Your personal AI assistant to study smarter",
  ai_tools: "AI Tools",
  quick_access: "Quick Access",

  // Features
  summary_title: "AI Summary",
  summary_sub: "Summarize your documents",
  quiz_title: "AI Quiz",
  quiz_sub: "Test your knowledge",
  plan_title: "Study Plan",
  plan_sub: "Plan your revisions",
  explain_title: "Explain",
  explain_sub: "Understand a text",
  solve_title: "Exercises",
  solve_sub: "Solve step by step",
  flashcards_title: "Flashcards",
  flashcards_sub: "Memorize quickly",
  chat_title: "AI Chat",
  chat_sub: "Questions about your course",

  // Auth
  login: "Sign In",
  signup: "Create Account",
  email: "Email",
  password: "Password",
  confirm_password: "Confirm Password",
  no_account: "No account?",
  already_account: "Already have an account?",
  login_failed: "Login failed",
  signup_failed: "Signup failed",
  login_subtitle: "Sign in to continue",
  signup_subtitle: "Join StudyAI for free",

  // Summary
  summary_screen_title: "AI Summary",
  text_to_summarize: "Text to summarize",
  summarize_btn: "Summarize with AI",
  summarizing: "Summarizing...",
  summary_result: "Summary",

  // Quiz
  quiz_screen_title: "AI Quiz",
  quiz_subject: "Quiz subject",
  quiz_questions: "Number of questions",
  generate_quiz: "Generate quiz",
  generating: "Generating...",
  next_question: "Next question →",
  see_results: "See results",
  score: "Score",
  new_quiz: "New quiz",

  // Plan
  plan_screen_title: "Study Plan",
  subjects: "Subjects to study",
  add_subject: "Add a subject",
  exam_date: "Exam date",
  hours_per_day: "Study hours per day",
  generate_plan: "Generate my AI plan",
  generating_plan: "Generating...",
  save: "Save",
  saved: "Saved",
  new_plan: "New plan",
  ai_tips: "AI Tips",

  // Chat
  chat_screen_title: "AI Chat",
  select_course: "Select a course to start",
  choose_course: "Choose a course",
  chat_locked: "This chat is limited to the selected course. Off-topic questions will be rejected.",
  chat_placeholder: "Question about",
  chat_limited: "AI Chat · Questions limited to course",

  // Explain
  explain_title_screen: "Explain a Text",
  text_to_explain: "Text to explain",
  explain_btn: "Explain with AI",
  explaining: "Analyzing...",
  explanation: "Explanation",
  key_points: "Key Points",
  level: "Level",

  // Solve
  solve_title_screen: "Solve an Exercise",
  exercise_input: "Exercise to solve",
  solve_btn: "Solve with AI",
  solving: "Solving...",
  steps: "Solution Steps",
  final_solution: "Final Solution",

  // Flashcards
  flashcards_title_screen: "AI Flashcards",
  topic: "Flashcard topic",
  cards_count: "Number of cards",
  generate_flashcards: "Generate flashcards",
  question: "QUESTION",
  answer: "ANSWER",
  tap_to_flip: "Tap to flip",
  previous: "← Previous",
  next_card: "Next →",

  // Profile
  profile_title: "Profile",
  logout: "Sign Out",
  logout_confirm: "Do you really want to sign out?",
  cancel: "Cancel",
  language: "Language",
  select_language: "Choose a language",
  verified_account: "Verified account",
  history: "Session history",

  // Common
  error: "Error",
  new: "New",
  back: "Back",
  generated_by: "Generated by AI · GPT-4o-mini",
};